### PR TITLE
Use es5 code for prod. #758

### PR DESCRIPTION
**Pull request by theKashey**

### CODE REVIEW

**Comment by neoziro** [comment]
Why?

**Comment by theKashey** [comment]
We do not transpile code to es5 cos we have to use es6 classes to work with es6 classes. 
Not sure it will be easy to use two separate Babel configs for this task.

**Comment by neoziro** [comment]
@theKashey please let me do it, build is my kind of stuff

**Comment by neoziro** [comment]
Continue in #761.

**Pull request closed without merging**
