### PR TITLE
Upgrade redbox-react dependency

### PR DESCRIPTION
**Pull request by montogeek**
To fix `prop-types` deprecation errors.
Tests run locally

### CODE REVIEW

**Comment by reintroducing** [comment]
Can we get this merged in please? The warnings are quite annoying, especially when trying to pinpoint what other packages may be causing warning as well. They never go away, no matter how much updating i do, because this is still present.

**Comment by gaearon** [comment]
@montogeek I added you to GH and npm collaborators so you should be able to get it merged and released!

**Comment by reintroducing** [comment]
Thank you Fernando and Dan, much appreciated.

**Comment by montogeek** [comment]
Released under `3.0.0-beta.7`, run `npm i -D react-hot-loader@next` to get it

**Pull request merged**
