### PR TITLE
Add hook for webpack statusHandler

### PR DESCRIPTION
**Pull request by natew**
Probably not ideal, but would resolve: https://github.com/gaearon/react-hot-loader/issues/993#issuecomment-392380403

### CODE REVIEW

**Comment by theKashey** [comment]
Do you might need before and after hooks?

Probably you need only `before`.
Probably it should be placed inside `updateInstances` to be more "not only webpack" compliant.

In case then you want to land a peace for webpack HMR I would propose another build

```js
> App.js
// addStatusHandler does not "accept" the changes, but could "observe"
module.hot.addStatusHandler(status => { do-whatever-you-want });
export default App;

> AppImporter.js
import App from './App';
// HMR will be accepted and stopped here
export default hot(App);

> index.js
import App from './AppImporter.js'
```

or, you can use anther "hack", by creating anther parent for App.js, which could observe the changes.
```js
> observer.js
import './App';  // you are _another_ parent module for the App.js.

module.hot.addStatusHandler(status => { do-whatever-you-want });
module.hot.accept(); //you have to accept the change
```

**Comment by theKashey** [comment]
Also please double check will just a "file structure" solution work for you.

**Comment by natew** [comment]
Adding an extra file above worked for me, thank you!

**Comment by theKashey** [comment]
Glad that you are problem got solved.
Lets pause, but not close, this PR for a while - it should be a bit rethinked before the merge, as long we will not be able to revert published change.

**Pull request closed without merging**
