### PR TITLE
Feat: Webpack injector

### PR DESCRIPTION
**Pull request by theKashey**
This PR is aimed to __implement  react RFC__ https://github.com/reactjs/rfcs/pull/74

As long as there is no activity on the original RFC, and there is no way to introduce that comparison to the already published version I am going to....

Use webpack loader to inject necessary changes into the React-Dom

🙌 🙌 🙌 🙌 🙌 🙌 

And it's actually working, letting us support any React Feature from the past or the future.

### React.lazy
(build-in)It would `import` lazy automaticaly, providing auto-reloading of the changed chunks.

### React.memo
(requires patch) Now it could deep-force-update even memo-ed components, working with fiber directly. (landing additional prop on memoizedProps to bypass shallow equal)

### React.forwardRef
(requires patch) Now it could update components, working with fiber directly

### Hooks
(requires patch) Could work with hooks with `pureSFC` enabled, or `ignoreSFC` activated

### CODE REVIEW

**Comment by neoziro** [comment]
It is **AWESOME**, I like the idea to monkey patch React 👌

**Comment by Bnaya** [comment]
Dose both babel plugin and webpack loader are required for it to work?
Or just the loader?

**Comment by theKashey** [comment]
- babel is required to update class-component methods
- webpack is required to support memo, and `ignoreSFC` mode, which will enable hooks.

**Comment by theKashey** [comment]
Lets discuss all the problems in https://github.com/gaearon/react-hot-loader/issues/1088

**Pull request merged**
