### PR TITLE
refactor: modernize packages

### PR DESCRIPTION
**Pull request by neoziro**
Use lerna, jest, and modern stuff.

### CODE REVIEW

**Comment by theKashey** [comment]
Prettier is a magic.
Looking good, but I am not sure it will compile.
Anyway - good to merge, and I'll fix pipeline during my daylight time.

**Comment by neoziro** [comment]
@theKashey I simplified tests, run prettier and added scripts to compile packages globally. I will find a way to run test on different Babel configurations.

**Comment by theKashey** [comment]
Sure. Are you done for today?

**Comment by neoziro** [comment]
@theKashey yes I will fix build and it is OK for me.

**Comment by theKashey** [comment]
Ok. Ready to merge?

**Comment by neoziro** [comment]
@theKashey no

**Comment by theKashey** [comment]
Ok. Then it is my time to continue fixes.

**Comment by neoziro** [comment]
@theKashey it should be OK now

**Comment by neoziro** [comment]
@theKashey can you go on Google Hangouts please?

**Comment by neoziro** [comment]
@theKashey ready to merge, diff is because Babel configuration is not fixed to a specify set of plugin `"node": "current"`. Nothing important.

**Comment by neoziro** [comment]
@theKashey using a Babel "env" config standard we have some tests that are not passing. I think it is a problem because it is the most used preset.

**Comment by theKashey** [comment]
What about keeping `boilerplate` inside? 
RHL is a tricky thing, and it is better to test change against some implementation, with proper instrumentation (babel or webpack).
In the same time - it is a good way to ship a boilerplate as an example.

**Pull request merged**
