### PR TITLE
chore(deps): update lodash

### PR DESCRIPTION
**Pull request by kontrollanten**
Solves this vuln warning https://snyk.io/vuln/SNYK-JS-LODASHMERGE-173732

I haven't verified this manually, just ran through the tests.

### CODE REVIEW

**Comment by theKashey** [comment]
It's still better to have `lodash.merge`, not the __big__ `lodash`. 
Please update, but not rename.

**Comment by kontrollanten** [comment]
`lodash.merge` haven't been updated. Isn't webpack tree shaking off the other parts when we just import `lodash/merge`?

**Comment by theKashey** [comment]
It's more about the dev bundle size, that runtime bundle size. But you are right - it was not updated, so you went the right way.

**Comment by dominykas** [comment]
It seems the build failed on node 8 - can someone re-run that please, so that this gets published? (it passed on node 10, so is this a flaky test or smth?)

**Comment by kontrollanten** [comment]
When I run the tests locally at node 8.15.1 everything passes, so it seems to be a flaky test.

**Comment by theKashey** [comment]
A flake.

**Pull request merged**
