### PR TITLE
Added @hot-loader/react-dom which is missing

### PR DESCRIPTION
**Pull request by theajr**
@gaearon 

In `examples/typescript`, `@hot-loader/react-dom` was missing in `package.json` which is required as we are using it as alias for react-dom.
Fixed some auto fixable vulnerabilities by running `npm audit fix`

### CODE REVIEW

**Comment by theKashey** [comment]
`package.lock` is not supposed to be here 😅

**Comment by theajr** [comment]
@theKashey Removed package lock file!

**Comment by theKashey** [comment]
Good job!
There is another TypeScript related issue you might like - https://github.com/gaearon/react-hot-loader/issues/1359 (but you don't have to)

**Comment by theajr** [comment]
Sure, I will check it out!

**Pull request merged**
