### PR TITLE
Simplify TypeScript configuration (updated)

### PR DESCRIPTION
**Pull request by Akuukis**
Quick work:
* took #996 as a base for working typescript example,
* upgraded from Webpack 3 to Webpack 4 and fixed configs,
* upgraded other dependencies to current newest,
* locked (remove `^`) babel dependencies because it's still in beta,
* rebased to new `master`,
* add support for `async` & `await` syntax (EDIT: amended later),
* tested and still working, faster than ever :tada:

Though I should share this. Thanks @lostfictions for heavy lifting!

### CODE REVIEW

**Comment by theKashey** [comment]
Looking great, but many people will refuse to use beta babel 7.
Probably one should leave some message about it, as long _default_ package install will bring babel 6.

**Comment by Akuukis** [comment]
Makes sense. Should we add warning to README and merge, or leave this PR until babel 7 becomes stable?

**Comment by theKashey** [comment]
I have no idea when it will be done, so lets try just some notes in README

**Comment by Akuukis** [comment]
@theKashey are we good to proceed?

**Comment by theKashey** [comment]
All good, sorry just busy a bit in real world.

**Comment by theKashey** [comment]
I've found that some TS people _do not like_ babel. They could be ok-ish to add babel as a webpack loader, but dont want to replace TS by babel as a whole.
Let me move old readme to a separate file, and point it for all non-babel-7 customers.

**Pull request merged**
