### PR TITLE
Added { modules: false } step to the Getting Started docs

### PR DESCRIPTION
**Pull request by mildrenben**
I also had this issue: https://github.com/gaearon/react-hot-loader/issues/596

### CODE REVIEW

**Comment by theKashey** [comment]
We can not add it yet:
1. RHL will not work with env preset.
2. "modules" affects only one thing - will webpack auto re-require "accepted" module, or you will have to call require by your own.

Actually, currently RHL's readme is not asking to enable harmony modules, but listed examples does not contain re-requiring updated code - and that is a mistake we should fix.

**Comment by mildrenben** [comment]
RHL _does_ work with env though. I'm using it right now. It only works with `modules: false`.

**Comment by theKashey** [comment]
@mildrenben if you will specify the target as a modern browser - RHL will blow up whole application due to some issues with non-transpiled arrow functions.
Anyway - you named the second step as the third one.
Please check numeration, and I'll be quite keen if you will include few words about different behaviours for different `modules` mode.

**Comment by coffenbacher** [comment]
There's a typo here, missing `]` in the first line

```
{
  "presets": [["env", { "modules": false }],
  "plugins": ["react-hot-loader/babel"]
}
```

**Comment by neoziro** [comment]
This isn't required in v4 anymore. https://github.com/gaearon/react-hot-loader/tree/next

**Pull request closed without merging**
