### PR TITLE
feat: errorReporter parameter

### PR DESCRIPTION
**Pull request by davidpfahler**
~~Sorry for the edits in Changelog. Some line ending problem in git. Maybe someone can help me out here.~~

This allows you to specify an npm module to be used as an error reporter.

### CODE REVIEW

**Comment by cgarvis** [comment]
:+1:

**Comment by dzannotti** [comment]
+1

**Comment by qimingweng** [comment]
:+1:

**Comment by gaearon** [comment]
We’ll use official error boundary capabilities in React when they become available. Some initial work is already there in 15.0, and 15.1 will handle more cases. Closing for this reason.

You can track error boundaries in https://github.com/facebook/react/issues/2461.

**Pull request closed without merging**
