### PR TITLE
Dependecy update 

### PR DESCRIPTION
**Pull request by MAPESO**
Hi, I'm the **new collaborator.** I did an update on all project dependencies.
Look @gaearon.

### CODE REVIEW

**Comment by gaearon** [comment]
Seems like CI is failing?

**Comment by MAPESO** [comment]
it seems there is a small problem with node 6 and 7. Error comes from travis.

**Comment by neoziro** [comment]
@MAPESO yes but we couldn't merge it without full green.

**Comment by MAPESO** [comment]
@neoziro  How can we do that? to update the dependencies

**Comment by neoziro** [comment]
Closed in favor of #638

**Pull request closed without merging**
