### PR TITLE
fix(error): Can't find variable: require [react-static]

### PR DESCRIPTION
**Pull request by dalisoft**
This [bug](https://github.com/nozzle/react-static/issues/1164) is caused by something, but referring to this line and i'm fixed (should work now)

### CODE REVIEW

**Comment by dalisoft** [comment]
I can confirm the bug fixed after modifying this line

**Comment by theKashey** [comment]
Could you double check - is there any file where `require` is not _undefined_, or for which files it is.

Probably this should be something like
```js
const r = typeof require !== 'undefined' ? require : (typeof __webpack_require__ !== 'undefined' ? __webpack_require__ : null);
if(!r) return;
```

But first we have to understand _why_ you have this problem.

**Comment by dalisoft** [comment]
The problem is causing by react-hot-loader within react-static. I don’t have fully controllable source code

**Comment by theKashey** [comment]
But we have to understand why you are the first one, who run into this issue.
@tannerlinsley - I heard you had some good time with React-Hot-Loader, so have you seen something like this before?

**Comment by J-F-Liu** [comment]
Does this mean that react-hot-loader will have no effect in react-static?

**Comment by theKashey** [comment]
No, disabling `webpack-loader` would lead to too hot reloading, with many false positives. Something should bound "things" to modules and their names.

**Comment by tannerlinsley** [comment]
I am pretty sure this happens when trying to dynamically `import()` a module during hot-module enabled development. Can anyone confirm?

**Comment by theKashey** [comment]
#1247 would solve this problem using `reactHotLoaderGlobal` variable.

**Pull request closed without merging**
