### PR TITLE
Remove redbox

### PR DESCRIPTION
**Pull request by wkwiatek**
Closes https://github.com/gaearon/react-hot-loader/issues/462

### CODE REVIEW

**Comment by calesce** [comment]
Looks good, let's also remove [this doc](https://github.com/gaearon/react-hot-loader/blob/9146001a9e8f076ad36669daa3c2bcdfb1631905/docs/TipsAndTricks.md). We still have #164 open in case we want to reconsider catching errors later on.

**Comment by AlexKvazos** [comment]
I don't think removing redbox is the fix, more likely we have to improve sourcemaps so that redbox can show useful information.

**Comment by wkwiatek** [comment]
@calesce Could you check the idea?

**Comment by mcrawshaw** [comment]
@wkwiatek @calesce anything holding this back?

**Comment by alexilyaev** [comment]
Guys, please merge this, or add an option to disable the RedBox (ideally an RedBox opt-in option).  
This is a long standing issue and it's annoying.

The way it is now, it forces us to add a hacky line when using `AppContainer`:
```
delete AppContainer.prototype.unstable_handleError;
```

or set a custom `errorReporter`, based on:  
https://github.com/gaearon/react-hot-loader/blob/master/docs/TipsAndTricks.md

Both of which should not be something a developer needs to think about when trying to setup hot-reloading, especially since it's a complicated process as it is.

**Comment by neoziro** [comment]
Hello, I am a new maintainer on the project (@gaearon). I think we can remove Redbox since it is not the responsibility of this project. We could give the choice to the user, but the natural way of reporting error is the console. I would like to merge it, what do you think?

**Pull request merged**
