### PR TITLE
Add prop types as dependency

### LINKED ISSUE #817: [v4] AppContainer depends on prop-types, which isn't installed
Should `prop-types` be added to `dependencies`? That's the recommendation for library usage as per its documentation: https://github.com/facebook/prop-types#how-to-depend-on-this-package

### PR DESCRIPTION
**Pull request by leanbalma**
Added `prop-types` as a dependency in `package.json`.
Resolves #817.

### CODE REVIEW

**Comment by theKashey** [comment]
Did you mean packages/react-hot-loader/packages.json? The one exposed as react-hot-loader to npm.

**Comment by theKashey** [comment]
👍

**Comment by leanbalma** [comment]
Thank you. Sorry about that.

**Comment by neoziro** [comment]
Thanks for it. Just a little problem, this project is using yarn. You have to install it with yarn, to do it just run `yarn` at the root of the project then go in `packages/react-hot-loader` and run `yarn add prop-types`.

**Comment by leanbalma** [comment]
Right. I have to include the `yarn.lock` file too :) Fixed.
Thanks.

**Pull request merged**
