### PR TITLE
filter out nulls

### PR DESCRIPTION
**Pull request by bennidhamma**
Do you mind merging this in? I have no idea why this nulls were getting into the children collection, but they were, and it was breaking my project, so this is a band-aid.

### CODE REVIEW

**Comment by theKashey** [comment]
Great work! But you provide any information about this nasty issue? 
Code code to reproduce, react(react-dom) version(is it 15?) 
How do you run into it?

**Comment by neoziro** [comment]
Hey thanks! Can you give us some information or write a test case by yourself?

**Comment by bennidhamma** [comment]
Hey y'all. I'm using react 16, react-jss, React Loadable, running webpack via the node API.

The basic behavior is that I'm using React Loadable to async load the top level components at each route level. The initial load works, and then when I navigate back and forth between two pages, this error was cropping up, but it was in a somewhat deep place in the component tree, which seemed a little odd.

If you like, I can dig a little more and inspect, but this did clear up the problem I was having.

Here is my package.json - note that it's even messier than usual because of this current refactor:

```
"dependencies": {
    "babel-plugin-transform-runtime": "6.23.0",
    "babel-polyfill": "6.23.0",
    "bootstrap": "4.0.0-alpha.6",
    "classnames": "2.2.5",
    "clipboard-js": "^0.3.5",
    "colors": "^1.1.2",
    "common-tags": "1.4.0",
    "concurrently": "3.5.0",
    "datauritoblob": "^1.0.0",
    "draft-js": "^0.10.2",
    "draft-js-export-markdown": "github:themaven-net/draft-js-export-markdown#fee014c47462c1f16791ef7d23e3c15454594309",
    "draft-js-utils": "^1.2.0",
    "express": "4.15.3",
    "history": "4.6.3",
    "hls.js": "0.7.10",
    "immutable": "3.8.1",
    "intersection-observer": "0.3.2",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "marked": "0.3.6",
    "material-ui": "^0.20.0",
    "material-ui-chip-input": "^0.18.5",
    "mdi": "2.0.46",
    "mobile-detect": "1.3.6",
    "modernizr": "3.5.0",
    "moment": "2.18.1",
    "ms": "2.0.0",
    "nuka-carousel": "^3.0.0",
    "postcss-modules": "0.8.0",
    "prop-types": "^15.5.10",
    "react": "^16.0.0",
    "react-cookie": "^0.4.8",
    "react-dom": "^16.0.0",
    "react-draft-wysiwyg": "themaven-net/react-draft-wysiwyg#2203c9fc0bee028daea70428ee23fba085d5df2d",
    "react-helmet": "5.1.3",
    "react-hot-loader": "next",
    "react-instagram-embed": "github:themaven-net/react-instagram-embed#2b7a13fe93716599dafeb197f72658a7a7b5ed9e",
    "react-js-pagination": "2.1.0",
    "react-jss": "^8.2.1",
    "react-jw-player": "^1.16.0",
    "react-loadable": "^5.3.1",
    "react-portal": "^3.1.0",
    "react-redux": "5.0.5",
    "react-router": "4.1.1",
    "react-router-dom": "4.1.1",
    "react-router-redux": "4.0.8",
    "react-sortable-hoc": "^0.6.8",
    "react-soundcloud-widget": "github:themaven-net/react-soundcloud-widget#815a3df3a6a61206ee452a00f71f691f1d7ecd48",
    "react-sparklines": "^1.7.0",
    "react-stripe-checkout": "2.4.0",
    "react-timeago": "^3.4.3",
    "react-transition-group": "^2.2.0",
    "react-twitter-widgets": "^1.6.1",
    "react-visibility-sensor": "^3.10.1",
    "react-widgets": "4.1.1",
    "react-widgets-moment": "^4.0.2",
    "react-youtube": "^7.4.0",
    "redux": "3.7.1",
    "redux-saga": "0.15.4",
    "resize-observer-polyfill": "^1.5.0",
    "scroll-into-view-if-needed": "1.1.0",
    "serialize-javascript": "1.3.0",
    "tether": "1.4.0",
    "urijs": "1.18.2",
    "write-file-webpack-plugin": "^4.2.0"
  },
  "devDependencies": {
    "babel-cli": "6.24.1",
    "babel-core": "6.25.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "7.1.2",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    "babel-plugin-flow-react-proptypes": "3.4.1",
    "babel-plugin-module-resolver": "2.7.1",
    "babel-plugin-react-transform": "2.0.2",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-postcss": "0.2.0",
    "babel-preset-env": "1.5.2",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-flow": "6.23.0",
    "babel-preset-react": "6.24.1",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-stage-0": "6.24.1",
    "better-npm-run": "0.0.15",
    "chai": "4.0.2",
    "clean-webpack-plugin": "^0.1.17",
    "continuation-local-storage": "^3.2.1",
    "css-loader": "0.28.4",
    "enzyme": "^2.9.1",
    "enzyme-redux": "^0.1.6",
    "eslint": "^4.11.0",
    "eslint-config-airbnb": "^15.0.2",
    "eslint-plugin-compat": "^1.0.4",
    "eslint-plugin-flowtype": "^2.35.1",
    "eslint-plugin-import": "^2.6.1",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "extract-text-webpack-plugin": "3.0.x",
    "file-loader": "0.11.2",
    "flow-bin": "0.49.1",
    "ignore-styles": "5.0.1",
    "jsdom": "11.0.0",
    "json-loader": "0.5.4",
    "karma": "^1.7.1",
    "karma-mocha": "^1.3.0",
    "karma-mocha-reporter": "^2.2.4",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.4",
    "less": "2.7.2",
    "less-loader": "2.2.3",
    "mocha": "^3.5.3",
    "node-sass": "4.5.3",
    "nodemon": "1.11.0",
    "phantomjs-polyfill": "0.0.2",
    "phantomjs-prebuilt": "2.1.14",
    "piping": "1.0.0-rc.4",
    "pm2": "2.5.0",
    "postcss": "6.0.4",
    "postcss-loader": "2.0.6",
    "prejss-styles-loader": "^1.0.0",
    "react-addons-test-utils": "15.6.0",
    "react-test-renderer": "^15.6.1",
    "react-transform-catch-errors": "1.0.2",
    "react-transform-hmr": "1.0.4",
    "redbox-react": "1.4.2",
    "rimraf": "2.6.1",
    "sass-loader": "6.0.6",
    "style-loader": "0.18.2",
    "uglifyjs-webpack-plugin": "1.1.1",
    "url-loader": "0.5.9",
    "webpack": "^3.10.0",
    "webpack-after-chunk-hash-plugin": "^1.0.0",
    "webpack-bundle-analyzer": "2.8.2",
    "webpack-dev-middleware": "^2.0.3",
    "webpack-dev-server": "^2.8.2",
    "webpack-hot-middleware": "^2.21.0",
    "webpack-hot-server-middleware": "^0.3.1",
    "webpack-manifest-plugin": "^1.3.2",
    "webpack-node-externals": "^1.6.0"
  },
  "engines": {
    "node": "8.9.1"
  }
```

**Comment by bennidhamma** [comment]
Here is an example of the error:

```
hotReplacementRender.js?845e:132 Uncaught TypeError: Cannot read property 'type' of null
    at children.children.map (hotReplacementRender.js?845e:132)
    at Array.map (<anonymous>)
    at mapChildren (hotReplacementRender.js?845e:122)
    at children.children.map (hotReplacementRender.js?845e:129)
    at Array.map (<anonymous>)
    at mapChildren (hotReplacementRender.js?845e:122)
    at mergeInject (hotReplacementRender.js?845e:149)
    at flow.forEach (hotReplacementRender.js?845e:193)
    at Array.forEach (<anonymous>)
    at hotReplacementRender (hotReplacementRender.js?845e:166)
```

**Comment by theKashey** [comment]
`wrapApp(hot(module)(App))`, 😢 et again - this function is for EXPORTS, not for imports or local variables :(
Use it to wrap `default export AppComponent` -> `export default hot(module)(AppComponent)`

**Comment by bennidhamma** [comment]
@theKashey, As I don't ever export AppComponent, I'm not sure how to translate this instruction.

HMR is working as I've configured it, with the exception of this issue with deeply nested elements somehow being null in this hotReplacementRender method.

Great discussion, and I'm happy to poke around a bit more, but is there anything really objectionable about the PR? Seems like a pretty basic, safe assertion to make...

**Comment by theKashey** [comment]
```js
Loadable.preloadReady().then(() => {
  ReactDOM.hydrate(wrapApp(hot(module)(App)), rootEl) <---
})
```
You have to move App to the external module, and use `hot` to make that module `hot`.
We are not 100% sure why it is impossible to mix `hot` and `react-dom`/render in one file, but it is impossible, actually resulting some problems with reconciler.

And there are no problems with PR. We just want to know how you get the error, and why we dont get it before.
Anyway - hotReplacementRender already got a code, about removing nulls from "first" children level. It sounds ok that we also should filter out nested children.

**Comment by bennidhamma** [comment]
Thanks Anton. I'll try pulling it out into a separate file and see if that
clears things up.

**Comment by bennidhamma** [comment]
OK, so I pulled AppComponent to it's own file:

```
...

const WrappedApp = () =>
  (<Provider store={store} key="provider">
    <BrowserRouter>
      <HistoryPusherWithRouter>
        <App store={store} client={client} />
      </HistoryPusherWithRouter>
    </BrowserRouter>
  </Provider>)

export default hot(module)(WrappedApp)
```

And here is client/index.js:

```
import 'babel-polyfill'
import AppComponent from 'client/AppComponent'
import React from 'react'
import ReactDOM from 'react-dom'
import Loadable from 'react-loadable';
import 'helpers/ArrayHelper'

const rootEl = document.getElementById('content')

Loadable.preloadReady().then(() => {
  ReactDOM.hydrate(<AppComponent />, rootEl)
})
```

Now, I get this error:

```
[HMR] bundle rebuilt in 5273ms
process-update.js?e13e:41 [HMR] Checking for updates on the server...
warning.js?0c47:10 The previous state received by the reducer has unexpected type of "Null". Expected argument to be an object with the following keys: "accessBehavior", "auth", "authorProfiles", "avatar", "channel", "channelGroups", "channelSettings", "channelUsers", "config", "conversation", "conversationModeration", "conversationStream", "conversationSummaries", "createConversation", "createMessage", "directMessages", "editMessage", "editStory", "findUsers", "log", "media", "membershipDefinitions", "messageModeration", "messageReaction", "messageReviewList", "messageSearch", "navigation", "notifications", "roomSettings", "streamSort", "time", "userAccountActions", "userEvents", "userModeration", "userModerationHistory", "userProfile", "userSettings", "userSuggestions", "userWelcome"
warning @ warning.js?0c47:10
combination @ combineReducers.js?c79d:110
computeNextEntry @ VM45220:2
recomputeStates @ VM45220:2
(anonymous) @ VM45220:2
dispatch @ createStore.js?6413:165
createStore @ createStore.js?6413:240
(anonymous) @ VM45220:3
(anonymous) @ VM45220:3
(anonymous) @ VM45220:2
(anonymous) @ applyMiddleware.js?be0b:28
(anonymous) @ VM45220:2
createStore @ createStore.js?6413:51
create @ create.js?32ee:31
(anonymous) @ AppComponent.js?20a6:36
(anonymous) @ 1555:218
(anonymous) @ http://[::1]:3000/dist/main.js:8048
__webpack_require__ @ http://[::1]:3000/dist/bootstrap.js:713
hotApply @ http://[::1]:3000/dist/bootstrap.js:637
cb @ process-update.js?e13e:66
(anonymous) @ process-update.js?e13e:82
Promise.then (async)
check @ process-update.js?e13e:81
module.exports @ process-update.js?e13e:42
processMessage @ client.js?07e4:251
handleMessage @ client.js?07e4:131
handleMessage @ client.js?07e4:94
process-update.js?e13e:114 [HMR] Updated modules:
process-update.js?e13e:116 [HMR]  - ./src/components/ChannelBar/ChannelBar.js
process-update.js?e13e:116 [HMR]  - ./src/containers/App/App.js
process-update.js?e13e:116 [HMR]  - ./src/client/AppComponent.js
process-update.js?e13e:116 [HMR]  - ./src/containers/index.js
process-update.js?e13e:116 [HMR]  - ./src/routes.jsx
process-update.js?e13e:116 [HMR]  - ./src/components/UserAccountActions/MaybeRenderActionModal.js
process-update.js?e13e:116 [HMR]  - ./src/components/RoomBar/RoomBar.js
process-update.js?e13e:116 [HMR]  - ./src/containers/Channel/Channel.js
process-update.js?e13e:116 [HMR]  - ./src/containers/Channel/LoadableChannel.js
process-update.js?e13e:121 [HMR] App is up to date.
logger.js?b2d4:29 React-hot-loader: fatal error caused by  ƒ Router() {
    var _temp, _this, _ret;

    _classCallCheck(this, Router);

    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_ke…  - no instrumentation found.  Please require react-hot-loader before React. More in troubleshooting.
error @ logger.js?b2d4:29
flow.forEach @ hotReplacementRender.js?845e:199
hotReplacementRender @ hotReplacementRender.js?845e:166
next @ hotReplacementRender.js?845e:182
flow.forEach @ hotReplacementRender.js?845e:204
hotReplacementRender @ hotReplacementRender.js?845e:166
next @ hotReplacementRender.js?845e:182
flow.forEach @ hotReplacementRender.js?845e:204
hotReplacementRender @ hotReplacementRender.js?845e:166
next @ hotReplacementRender.js?845e:182
flow.forEach @ hotReplacementRender.js?845e:204
hotReplacementRender @ hotReplacementRender.js?845e:166
exports.default @ hotReplacementRender.js?845e:226
componentWillReceiveProps @ AppContainer.dev.js?ce78:47
callComponentWillReceiveProps @ react-dom.development.js?cada:6389
updateClassInstance @ react-dom.development.js?cada:6575
updateClassComponent @ react-dom.development.js?cada:7848
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueForceUpdate @ react-dom.development.js?cada:6250
Component.forceUpdate @ react.development.js?99ee:255
getInstances.forEach.inst @ hot.dev.js?783d:32
setTimeout @ hot.dev.js?783d:32
setTimeout (async)
updateInstances @ hot.dev.js?783d:32
sourceModule.hot.addStatusHandler.status @ hot.dev.js?783d:44
hotSetStatus @ http://[::1]:3000/dist/bootstrap.js:232
hotApply @ http://[::1]:3000/dist/bootstrap.js:581
cb @ process-update.js?e13e:66
(anonymous) @ process-update.js?e13e:82
Promise.then (async)
check @ process-update.js?e13e:81
module.exports @ process-update.js?e13e:42
processMessage @ client.js?07e4:251
handleMessage @ client.js?07e4:131
handleMessage @ client.js?07e4:94
hotReplacementRender.js?845e:200 Uncaught Error: React-hot-loader: wrong configuration
    at flow.forEach (hotReplacementRender.js?845e:200)
    at Array.forEach (<anonymous>)
    at hotReplacementRender (hotReplacementRender.js?845e:166)
    at next (hotReplacementRender.js?845e:182)
    at flow.forEach (hotReplacementRender.js?845e:204)
    at Array.forEach (<anonymous>)
    at hotReplacementRender (hotReplacementRender.js?845e:166)
    at next (hotReplacementRender.js?845e:182)
    at flow.forEach (hotReplacementRender.js?845e:204)
    at Array.forEach (<anonymous>)
flow.forEach @ hotReplacementRender.js?845e:200
hotReplacementRender @ hotReplacementRender.js?845e:166
next @ hotReplacementRender.js?845e:182
flow.forEach @ hotReplacementRender.js?845e:204
hotReplacementRender @ hotReplacementRender.js?845e:166
next @ hotReplacementRender.js?845e:182
flow.forEach @ hotReplacementRender.js?845e:204
hotReplacementRender @ hotReplacementRender.js?845e:166
next @ hotReplacementRender.js?845e:182
flow.forEach @ hotReplacementRender.js?845e:204
hotReplacementRender @ hotReplacementRender.js?845e:166
exports.default @ hotReplacementRender.js?845e:226
componentWillReceiveProps @ AppContainer.dev.js?ce78:47
callComponentWillReceiveProps @ react-dom.development.js?cada:6389
updateClassInstance @ react-dom.development.js?cada:6575
updateClassComponent @ react-dom.development.js?cada:7848
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueForceUpdate @ react-dom.development.js?cada:6250
Component.forceUpdate @ react.development.js?99ee:255
getInstances.forEach.inst @ hot.dev.js?783d:32
setTimeout @ hot.dev.js?783d:32
setTimeout (async)
updateInstances @ hot.dev.js?783d:32
sourceModule.hot.addStatusHandler.status @ hot.dev.js?783d:44
hotSetStatus @ http://[::1]:3000/dist/bootstrap.js:232
hotApply @ http://[::1]:3000/dist/bootstrap.js:581
cb @ process-update.js?e13e:66
(anonymous) @ process-update.js?e13e:82
Promise.then (async)
check @ process-update.js?e13e:81
module.exports @ process-update.js?e13e:42
processMessage @ client.js?07e4:251
handleMessage @ client.js?07e4:131
handleMessage @ client.js?07e4:94
react-dom.development.js?cada:9747 The above error occurred in the <AppContainer> component:
    in AppContainer (created by HotExportedWrappedApp)
    in HotExportedWrappedApp

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

any ideas?

**Comment by theKashey** [comment]
@bennidhamma - RHL was not set by the time Router was rendered. This should not happen.
just import it in `index`, but dont use! The best way - import it as a first import.

If it will fix the issue - __rollback__ the changes and share the source code. We have to handle this automagically.

**Comment by bennidhamma** [comment]
tried that, but still doesn't work:

```js
import 'react-hot-loader'
import 'babel-polyfill'
import AppComponent from 'client/AppComponent'
import React from 'react'
import ReactDOM from 'react-dom'
import Loadable from 'react-loadable';
import 'helpers/ArrayHelper'

const rootEl = document.getElementById('content')

Loadable.preloadReady().then(() => {
  ReactDOM.hydrate(<AppComponent />, rootEl)
})
```

:(

**Pull request merged**
