### PR TITLE
need moar this

### PR DESCRIPTION
**Pull request by theKashey**
Just adding more this for #969

### CODE REVIEW

**Comment by theKashey** [comment]
@timneutkens - could you try master branch? Is this the last fix we all need?

**Comment by timneutkens** [comment]
Solves the issue we had.

**Comment by theKashey** [comment]
Ok, lets wait for #975 and then release a new version.

**Comment by Kaishiyoku** [comment]
Same issue here with this5 - when will this fix be released?

**Comment by theKashey** [comment]
@Kaishiyoku - hold my beer

**Comment by theKashey** [comment]
version 4.2.0 - released.

**Pull request merged**
