### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by moondef**
#866

### CODE REVIEW

**Comment by theKashey** [comment]
I am not sure that this is enough. Could you please drop the [old readme](https://github.com/gaearon/react-hot-loader/blob/v4.0.0-beta.19/packages/react-stand-in/README.md) for stand-in, the old link actually refers to, in this directory?

**Comment by moondef** [comment]
@theKashey done

**Comment by theKashey** [comment]
I mean - physically drop(restore) the file in the correct place. 
And you should not refer to the "obsolete branch", or even "current branch name". Sooner or later _next_ will become _master_, and what then?

**Comment by neoziro** [comment]
We should not refer stand-in anymore, please replace next by master and point to an existing file.

**Pull request closed without merging**
