### PR TITLE
chore(tests): add e2e setup with puppeteer

### PR DESCRIPTION
**Pull request by phil-lgr**
initial setup for jest-puppeteer with one working example for #1106

### CODE REVIEW

**Comment by phil-lgr** [comment]
In one terminal
```
cd examples/webpack
yarn && yarn start
```

and then in the main terminal
```
yarn
yarn test:modern
```

**Comment by phil-lgr** [comment]
- [ ] fix CONTRIBUTING.md which is outdated
- [ ] confirm placements of e2e test files (in /tests/e2e)
- [ ] confim if we need a `yarn test:e2e` command or not
- [ ] on that example should we run the tests?

**Comment by phil-lgr** [comment]
Ok I need some help. There is the points above.. 

I normally write puppeteer tests like this:

```js
import puppeteer from 'puppeteer'

import { navigateToApp } from './navigate-to-app'
import { puppeteerConfig } from '../../testConfig/puppeteer'

describe('in the Webpack test suite', async () => {
  let page
  let browser

  beforeAll(async () => {
    browser = await puppeteer.launch(puppeteerConfig.launchOptions)
    page = await browser.newPage()
  })

  it('should display the correct title', async () => {
    await navigateToApp(page, puppeteerConfig.appURL)
    await expect(await page.title()).toMatch('Webpack App')
  })

  afterAll(async () => {
    browser.close()
  })
})
```

I've updated my bullet points. Let me know if you can answer some of them!

**Comment by theKashey** [comment]
@neoziro - you might be the best person to review `jest-puppeteer` integration :)

**Comment by theKashey** [comment]
Just a first step. Do you have a plan for a test, how it would work?
I was thinking about running a real `webpack-dev-server` and changing real files, so doing _real_ things.
`jest-puppeteer` is a better choice for this case than `Cypress`, but I have to experience with it -.

**Comment by phil-lgr** [comment]
> Just a first step. Do you have a plan for a test, how it would work?
I was thinking about running a real webpack-dev-server and changing real files, so doing real things.

I don't have other ideas other than this.. maybe jest gurus have a way to simulate that.

We could use the example webpack (/example/webpack) as our testing ground?

On CI the script would run the example/webpack in dev mode (so `yarn  && yarn start`), run the e2e tests.. and then poke with the files and wait/expect changes to be visible from chrome

**Comment by theKashey** [comment]
on ci you might use `concurrently` to webpack and jest in a parallel, and kill both(`--kill-others-on-fail`) when any of them exists.

**Comment by phil-lgr** [comment]
I have some time today.

I will add the ci config and try to change real files and detect the changes

**Comment by theKashey** [comment]
Oh, e2e tests would have saved me from publishing 4.8.1 with runtime exception out of the box :(

**Comment by theKashey** [comment]
Any further activity?

**Comment by phil-lgr** [comment]
Ok I will have a look this week, I’m writing a bunch of e2e tests these days.. I’ll update the branch

**Comment by phil-lgr** [comment]
I'm updating my branch right now, update incoming

**Comment by phil-lgr** [comment]
I'm afraid I need to give up, I'm hitting setup issues over and over again, all my jest-puppeteer setup are on @babel v7 with recent version of webpack.. and all my tests are written in .ts .tsx, just trying to run the webpack example and it doesnt run anymore:

```
The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:775
    throw err;

```

**Comment by phil-lgr** [comment]
I just tried for multiple hours to get the basics up and running.. and I don't have more time with all my consulting work. Sadly I won't be able to work on it soon.

**Pull request closed without merging**
