### PR TITLE
drop `hot` calls for prod mode

### LINKED ISSUE #1080: Using `module` for `hot` cancels some webpack optimizations in prod
```js
import React from 'react'
import { hot } from 'react-hot-loader'

const App = () => <div>Hello World!</div>

export default hot(module)(App)
```

This code uses `module` variable. This cancels at least [concatenateModules](https://webpack.js.org/configuration/optimization/#optimization-concatenatemodules) optimization (enabled in prod mode)
https://github.com/webpack/webpack/blob/af90df9998c2aec0a9f8fbb6c488a0c423b1a331/lib/optimize/ModuleConcatenationPlugin.js#L104

Seems like bundles that using RHL has the worst size and eval-performance because some webpack-optimizations just not applying

I've created a simple babel-plugin, that replaces `export default hot(module)(App)` by `export default App` and it dropped **200kb** from total bundle size by dropping useless code and by ModuleConcatenationPlugin stuff.
Notу that we have only 8 places where we using `hot` in our code. 200kb for only 8 places... not bad...

But it seems like a hack... I think, that the problem should be solved on RHL side.

I can create a PR to `babel.prod.js` with replacing `hot(module)(App)` by `App`

### PR DESCRIPTION
**Pull request by smelukov**
closes #1080

### CODE REVIEW

**Comment by smelukov** [comment]
Now supports all import cases:
```
import { hot } from 'react-hot-loader'
import { hot as namedHot } from 'react-hot-loader'
import * as RHL from 'react-hot-loader'
```

**Comment by theKashey** [comment]
Amazing! Just amazing!

**Comment by smelukov** [comment]
Are there any comments for this? )

**Comment by theKashey** [comment]
Gonna handle this and another pending PRs on weekends.

**Comment by theKashey** [comment]
Released in 4.3.12

**Comment by smelukov** [comment]
Thanks :)

**Comment by edmorley** [comment]
Hi!

I don't see any change in the babel output when using default exports (eg `export default hot(module)(App)`). Is this expected?

**Comment by smelukov** [comment]
@edmorley Hi!
The output will change only in the production build (when `NODE_ENV` is `production`)

**Comment by edmorley** [comment]
Yup, this is with NODE_ENV=production, and webpack mode production.

**Comment by smelukov** [comment]
@edmorley thank you! I've investigated this and find out that hot-dropping may not work with some babel-presets configuration.
Fix in https://github.com/gaearon/react-hot-loader/pull/1093

**Pull request merged**
