### PR TITLE
migrate to semicolon-ish code style

### PR DESCRIPTION
**Pull request by theKashey**
Implements #1241 

- semicolons are recommend by TC39 and _future proof
- automatic semicolon injection is a dangerous thing and we had to use it for root (untranspiled) files to prevent runtime exception (shipped once a broken version to prod).
- original package creator was more about `semi:true` and `react` itself uses `semi`
- this is the only package under my governance, which does not use `semi`, and it was always a bit painful for me to fight with my coding habbits (and another maintainer approved the changes)

### CODE REVIEW

**Comment by JustFly1984** [comment]
just why?

**Comment by theKashey** [comment]
@JustFly1984 - updated description.

**Comment by JustFly1984** [comment]
I have a question: can I use Typescript without semicolons? The other issue I have with semicolons is that it will point git blame on the author who inserted a semicolon, instead of original author of the code. same issue with last comma in the list.

**Comment by theKashey** [comment]
> can I use Typescript without semicolons?

It would be much more safe to use TS without semi than JS. Still there are valid, IIFE-like cases when you have to insert semicolon thoughtfully, and no linter/language could help you.

> The other issue I have with semicolons is that it will point git blame on the author who inserted a semicolon

Usually it's not a problem. You are inserting a line as a complete thing - with(or without) semicolon since the beginning. 

If you are pointing on changing _blame_ for RHL source codes - this is not a first project-wide transformation we did, and (I hope) _blame_ attribution is not so important for all the people contributed into RHL.

**Comment by theKashey** [comment]
Anyway, let's confirm the last sentence.

**Comment by theKashey** [comment]
So 🤷‍♂️- nobody object

**Pull request merged**
