### PR TITLE
fix: props merge order && willUpdate. #967

### PR DESCRIPTION
**Pull request by theKashey**
Continuation of https://github.com/gaearon/react-hot-loader/pull/967

### CODE REVIEW

**Comment by timneutkens** [comment]
Verified that this solves the issue we were seeing. Thanks @theKashey 🙏

**Comment by theKashey** [comment]
It's too late for me to merge and release. @neoziro, might be you could handle it?

**Comment by timneutkens** [comment]
Thank you very much @theKashey 👍🙌 Waiting on this to release Next.js 6.0.1 🙏

**Comment by neoziro** [comment]
@theKashey I am on it!

**Pull request merged**
