### PR TITLE
@next refers old version (v4.5.3)

### PR DESCRIPTION
**Pull request by mtsmfm**
https://www.npmjs.com/package/react-hot-loader

image

### CODE REVIEW

**Comment by theKashey** [comment]
👍

**Comment by mtsmfm** [comment]
@theKashey next is currently not next and beta is not beta I think.
Do you have any plans to remove these tags?

**Comment by theKashey** [comment]
There is a plan to remove RHL :) Not joking - this package is very close to be deprecated.

**Comment by mtsmfm** [comment]
I know this issue https://github.com/gaearon/react-hot-loader/issues/1453 though,
I think react-refresh is still experimental and we'll need some months to deprecate.

**Comment by theKashey** [comment]
It's already used in `nextjs` and `react-native`, and even RHL uses it from some point of view.

**Comment by mtsmfm** [comment]
I see.

Anyway, this package is not deprecated yet, removing old tags can avoid confusing from now I think.

https://docs.npmjs.com/cli/dist-tag

**Pull request merged**
