### PR TITLE
Handle lazy indeterminate static properties

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by theKashey** [comment]
No tests 😭
Things like this should be covered by tests, to not to be suddenly broken in the future.

**Comment by taion** [comment]
@theKashey 

I'm back with more "fun" on weird React features used in Relay.

Relay now does this: https://github.com/facebook/relay/commit/0573d773af1632dd70b03311cfc30c9b5eb4c0e6

So... we need to also lazily proxy over `getDerivedStateFromProps`. Sigh.

**Comment by taion** [comment]
Sorry, tests forthcoming! Wanted to get the PR up to point people at what was happening.

**Comment by taion** [comment]
Updated the test case to cover this.

**Comment by theKashey** [comment]
👍

**Comment by theKashey** [comment]
@taion - ok to merge? Is this the only change you need?

**Comment by taion** [comment]
Yup, this is the only change. I’m not 100% sure that my use of `transferStaticProps` there is correct, but it’s probably okay. At least, it fixes the problem I see.

**Comment by theKashey** [comment]
It sounds to be correct. Anyway - I should not break anything.

**Comment by theKashey** [comment]
v 4.3.1

**Pull request merged**
