### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by jupl**

### CODE REVIEW

**Comment by calesce** [comment]
Hey, thanks for taking the time to do this. I think it'd be better to have type definitions in [definitely-typed](https://github.com/DefinitelyTyped/DefinitelyTyped), rather than being maintained by us, so I'd recommend making a PR there.

@nfcampos or @hedgerh, do you agree/disagree?

**Comment by nfcampos** [comment]
I'm not familiar with Typescript enough to know whether the definitions belong here or in the `definitely-typed` repo.

**Comment by Kovensky** [comment]
It looks like DefinitelyTyped [prefers](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/README.md#create-a-new-package) that libraries bundle their own types:

> If you are the library author, or can make a pull request to the library, bundle types instead of publishing to DefinitelyTyped.

There are definitions in DefinitelyTyped now (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12632), though, so this could be closed.

**Comment by calesce** [comment]
Thanks @Kovensky. Even though we have a small API, I still think it's better to have in `DefinitelyTyped`, and the typedefs are now there. Thanks again for your effort, @jupl.

**Pull request closed without merging**
